import Player from "./player";
import Prompt from "./prompt";
import GameSettings from "./gameSettings";

export default class GameState {
    players: Player[];
    promptOptions: Prompt[];
    selectedPrompt: Prompt | undefined;
    givenAnswers;
    gameIsRunning: boolean;
    settings: GameSettings;

    constructor() {
        this.players = [];
        this.settings = new GameSettings();
        this.givenAnswers = new Set;
        this.gameIsRunning = false;
        this.selectedPrompt = undefined;
        this.promptOptions = [
            //new Prompt('Randomly Selected Colours', ['Red', 'Blue', 'Green', 'Yellow']),
            new Prompt('US States', [
                'Alabama',
                'Alaska',
                'Arizona',
                'Arkansas',
                'California',
                'Colorado',
                'Connecticut',
                'Delaware',
                'Florida',
                'Georgia',
                'Hawaii',
                'Idaho',
                'Illinois',
                'Indiana',
                'Iowa',
                'Kansas',
                'Kentucky',
                'Louisiana',
                'Maine',
                'Maryland',
                'Massachusetts',
                'Michigan',
                'Minnesota',
                'Mississippi',
                'Missouri',
                'Montana',
                'Nebraska',
                'Nevada',
                'New Hampshire',
                'New Jersey',
                'New Mexico',
                'New York',
                'North Carolina',
                'North Dakota',
                'Ohio',
                'Oklahoma',
                'Oregon',
                'Pennsylvania',
                'Rhode Island',
                'South Carolina',
                'South Dakota',
                'Tennessee',
                'Texas',
                'Utah',
                'Vermont',
                'Virginia',
                'Washington',
                'West Virginia',
                'Wisconsin',
                'Wyoming',
            ]),
            new Prompt('Elements in the Periodic Table', [
                'Hydrogen',
                'Helium',
                'Lithium',
                'Beryllium',
                'Boron',
                'Carbon',
                'Nitrogen',
                'Oxygen',
                'Fluorine',
                'Neon',
                'Sodium',
                'Magnesium',
                'Aluminum',
                'Silicon',
                'Phosphorus',
                'Sulfur',
                'Chlorine',
                'Argon',
                'Potassium',
                'Calcium',
                'Scandium',
                'Titanium',
                'Vanadium',
                'Chromium',
                'Manganese',
                'Iron',
                'Cobalt',
                'Nickel',
                'Copper',
                'Zinc',
                'Gallium',
                'Germanium',
                'Arsenic',
                'Selenium',
                'Bromine',
                'Krypton',
                'Rubidium',
                'Strontium',
                'Yttrium',
                'Zirconium',
                'Niobium',
                'Molybdenum',
                'Technetium',
                'Ruthenium',
                'Rhodium',
                'Palladium',
                'Silver',
                'Cadmium',
                'Indium',
                'Tin',
                'Antimony',
                'Tellurium',
                'Iodine',
                'Xenon',
                'Cesium',
                'Barium',
                'Lanthanum',
                'Cerium',
                'Praseodymium',
                'Neodymium',
                'Promethium',
                'Samarium',
                'Europium',
                'Gadolinium',
                'Terbium',
                'Dysprosium',
                'Holmium',
                'Erbium',
                'Thulium',
                'Ytterbium',
                'Lutetium',
                'Hafnium',
                'Tantalum',
                'Wolfram',
                'Rhenium',
                'Osmium',
                'Iridium',
                'Platinum',
                'Gold',
                'Mercury',
                'Thallium',
                'Lead',
                'Bismuth',
                'Polonium',
                'Astatine',
                'Radon',
                'Francium',
                'Radium',
                'Actinium',
                'Thorium',
                'Protactinium',
                'Uranium',
                'Neptunium',
                'Plutonium',
                'Americium',
                'Curium',
                'Berkelium',
                'Californium',
                'Einsteinium',
                'Fermium',
                'Mendelevium',
                'Nobelium',
                'Lawrencium',
                'Rutherfordium',
                'Dubnium',
                'Seaborgium',
                'Bohrium',
                'Hassium',
                'Meitnerium',
                'Darmstadtium',
                'Roentgenium',
                'Copernicium',
                'Nihonium',
                'Flerovium',
                'Moscovium',
                'Livermorium',
                'Tennessine',
                'Oganesson',
            ]),
            new Prompt("Tube Stations", [
                'Acton Town',
                '',
                '',
                '',
                'Aldgate',
                '',
                '',
                '',
                '',
                'Aldgate East',
                '',
                '',
                '',
                'Alperton',
                'Amersham',
                '',
                '',
                '',
                'Angel',
                'Archway',
                '',
                '',
                '',
                '',
                '',
                'Arnos Grove',
                'Arsenal',
                '',
                '',
                '',
                'Baker Street',
                'Balham',
                'Bank',
                'Barbican',
                'Barking',
                '',
                '',
                '',
                'Barkingside',
                'Barons Court',
                '',
                '',
                '',
                'Battersea Power Station',
                'Bayswater',
                'Becontree',
                'Belsize Park',
                'Bermondsey',
                'Bethnal Green',
                'Blackfriars',
                'Blackhorse Road',
                'Bond Street',
                'Borough',
                'Boston Manor',
                'Bounds Green',
                'Bow Road',
                'Brent Cross',
                'Brixton',
                'Bromley-by-Bow',
                'Buckhurst Hill',
                'Burnt Oak',
                'Caledonian Road',
                'Camden Town',
                'Canada Water',
                'Canary Wharf',
                'Canning Town',
                'Cannon Street',
                'Canons Park',
                'Chalfont & Latimer',
                'Chalk Farm',
                'Chancery Lane',
                'Charing Cross',
                'Chesham',
                'Chigwell',
                'Chiswick Park',
                'Chorleywood',
                'Clapham Common',
                'Clapham North',
                'Clapham South',
                'Cockfosters',
                'Colindale',
                'Colliers Wood',
                'Covent Garden',
                'Croxley',
                'Dagenham East',
                'Dagenham Heathway',
                'Debden',
                'Dollis Hill',
                'Ealing Broadway',
                'Ealing Common',
                'Earls Court',
                '',
                '',
                'East Acton',
                'East Finchley',
                'East Ham',
                '',
                '',
                '',
                'East Putney',
                'Eastcote',
                '',
                '',
                '',
                'Edgware',
                'Edgware Road',
                'Edgware Road',
                '',
                '',
                '',
                '',
                'Elephant & Castle',
                '',
                '',
                '',
                'Elm Park',
                'Embankment',
                '',
                '',
                '',
                '',
                '',
                'Epping',
                'Euston',
                '',
                '',
                '',
                '',
                'Euston Square',
                '',
                '',
                '',
                '',
                'Fairlop',
                'Farringdon',
                '',
                '',
                '',
                '',
                'Finchley Central',
                '',
                '',
                '',
                '',
                'Finchley Road',
                '',
                '',
                '',
                'Finsbury Park',
                '',
                '',
                '',
                'Fulham Broadway',
                'Gants Hill',
                'Gloucester Road',
                '',
                '',
                '',
                '',
                'Golders Green',
                'Goldhawk Road',
                '',
                '',
                '',
                'Goodge Street',
                'Grange Hill',
                'Great Portland Street',
                '',
                '',
                '',
                '',
                'Greenford',
                'Green Park',
                '',
                '',
                '',
                '',
                'Gunnersbury',
                'Hainault',
                'Hammersmith',
                '',
                '',
                '',
                '',
                '',
                '',
                'Hammersmith',
                '',
                '',
                '',
                'Hampstead',
                'Hanger Lane',
                'Harlesden',
                'Harrow & Wealdstone',
                'Harrow-on-the-Hill',
                'Hatton Cross',
                'Heathrow Terminals 2 & 3',
                '',
                '',
                '',
                '',
                'Heathrow Terminal 4',
                '',
                '',
                '',
                'Heathrow Terminal 5',
                'Hendon Central',
                'High Barnet',
                'Highbury & Islington',
                'Highgate',
                'High Street Kensington',
                '',
                '',
                '',
                'Hillingdon',
                '',
                '',
                '',
                'Holborn',
                '',
                '',
                '',
                'Holland Park',
                'Holloway Road',
                'Hornchurch',
                'Hounslow Central',
                'Hounslow East',
                'Hounslow West',
                'Hyde Park Corner',
                'Ickenham',
                '',
                '',
                '',
                'Kennington',
                'Kensal Green',
                'Kensington (Olympia)',
                '',
                '',
                '',
                '',
                'Kentish Town',
                'Kenton',
                '',
                '',
                '',
                'Kew Gardens',
                'Kilburn',
                'Kilburn Park',
                'Kingsbury',
                'Kings Cross St Pancras',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                'Knightsbridge',
                'Ladbroke Grove',
                '',
                '',
                '',
                'Lambeth North',
                '',
                '',
                '',
                'Lancaster Gate',
                'Latimer Road',
                '',
                '',
                '',
                '',
                '',
                '',
                'Leicester Square',
                '',
                '',
                '',
                '',
                '',
                'Leyton',
                'Leytonstone',
                'Liverpool Street',
                '',
                '',
                '',
                '',
                '',
                'London Bridge',
                '',
                '',
                '',
                'Loughton',
                'Maida Vale',
                'Manor House',
                '',
                '',
                '',
                'Mansion House',
                '',
                '',
                '',
                'Marble Arch',
                'Marylebone',
                '',
                '',
                '',
                'Mile End',
                '',
                '',
                '',
                '',
                'Mill Hill East',
                '',
                '',
                '',
                'Monument',
                '',
                '',
                '',
                'Moorgate',
                '',
                '',
                '',
                '',
                '',
                'Moor Park',
                '',
                '',
                '',
                'Morden',
                'Mornington Crescent',
                'Neasden',
                '',
                '',
                '',
                'Newbury Park',
                'Nine Elms',
                'North Acton',
                'North Ealing',
                'North Greenwich',
                'North Harrow',
                'North Wembley',
                'Northfields',
                '',
                '',
                '',
                'Northolt',
                'Northwick Park',
                'Northwood',
                'Northwood Hills',
                'Notting Hill Gate',
                '',
                '',
                '',
                '',
                'Oakwood',
                '',
                '',
                '',
                '',
                'Old Street',
                '',
                '',
                '',
                'Osterley',
                '',
                '',
                '',
                'Oval',
                '',
                '',
                '',
                'Oxford Circus',
                '',
                '',
                '',
                '',
                'Paddington',
                '',
                '',
                '',
                'Paddington',
                '',
                '',
                '',
                'Park Royal',
                '',
                '',
                '',
                'Parsons Green',
                'Perivale',
                'Piccadilly Circus',
                '',
                '',
                '',
                'Pimlico',
                'Pinner',
                'Plaistow',
                '',
                '',
                '',
                'Preston Road',
                '',
                '',
                '',
                'Putney Bridge',
                '',
                '',
                '',
                '',
                'Queens Park',
                'Queensbury',
                'Queensway',
                'Ravenscourt Park',
                'Rayners Lane',
                '',
                '',
                '',
                'Redbridge',
                'Regents Park',
                'Richmond',
                'Rickmansworth',
                'Roding Valley',
                '',
                '',
                '',
                'Royal Oak',
                '',
                '',
                '',
                'Ruislip',
                '',
                '',
                '',
                'Ruislip Gardens',
                'Ruislip Manor',
                '',
                '',
                '',
                'Russell Square',
                'St Jamess Park',
                '',
                '',
                '',
                '',
                'St Johns Wood',
                'St Pauls',
                '',
                '',
                '',
                'Seven Sisters',
                'Shepherds Bush',
                'Shepherds Bush Market',
                '',
                '',
                '',
                'Sloane Square',
                '',
                '',
                '',
                '',
                '',
                '',
                'Snaresbrook',
                'South Ealing',
                'South Harrow',
                'South Kensington',
                'South Kenton',
                'South Ruislip',
                '',
                '',
                '',
                'South Wimbledon',
                '',
                '',
                '',
                '',
                'South Woodford',
                '',
                '',
                '',
                'Southfields',
                'Southgate',
                'Southwark',
                'Stamford Brook',
                'Stanmore',
                'Stepney Green',
                '',
                '',
                '',
                'Stockwell',
                '',
                '',
                '',
                'Stonebridge Park',
                'Stratford',
                '',
                '',
                '',
                'Sudbury Hill',
                '',
                '',
                '',
                'Sudbury Town',
                '',
                '',
                '',
                'Swiss Cottage',
                'Temple',
                '',
                '',
                'Theydon Bois',
                'Tooting Bec',
                'Tooting Broadway',
                'Tottenham Court Road',
                '',
                '',
                '',
                'Tottenham Hale',
                'Totteridge & Whetstone',
                'Tower Hill',
                '',
                '',
                '',
                'Tufnell Park',
                'Turnham Green',
                '',
                '',
                '',
                'Turnpike Lane',
                'Upminster',
                'Upminster Bridge',
                'Upney',
                'Upton Park',
                'Uxbridge',
                'Vauxhall',
                'Victoria',
                'Walthamstow Central',
                'Wanstead',
                'Warren Street',
                'Warwick Avenue',
                'Waterloo',
                'Watford',
                'Wembley Central',
                'Wembley Park',
                'West Acton',
                'West Brompton',
                'West Finchley',
                'West Ham',
                'West Hampstead',
                'West Harrow',
                'West Kensington',
                'West Ruislip',
                'Westbourne Park',
                'Westminster',
                'White City',
                'Whitechapel',
                'Willesden Green',
                'Willesden Junction',
                'Wimbledon',
                'Wimbledon Park',
                'Wood Green',
                'Wood Lane',
                'Woodford',
                'Woodside Park',
            ].filter(item => item != '')),
            new Prompt("Tables in ACS", [
                'AirplaneOperatorView',
                'EmailTemplateOffices',
                'AirlineView',
                'CustomerPortalUserRefreshTokens',
                'DatabaseCheckIn',
                'PublishedItineraryLegLocations',
                'AirlineContactsView',
                'EmailTemplates',
                'AirlineAircraftSearchHistoryAirlineBaseCountries',
                'AircraftTypeDepartments',
                'CustomerPortalUsers',
                'AircraftView',
                'DuplicateCheckReceipts',
                'PendingBookingBridgerChecks',
                'AdditionalCostView',
                'EnquiryLegs',
                'CustomerPortalNotificationMessages',
                'StateTypes',
                'CloseReasonCategories',
                'UserTargets',
                'PriceExclusions',
                'AccountsCBFCustomerView',
                'CustomerCompetitiveAirlines',
                'CustomerPortalBookingLegs',
                'AirlineAircraftSearchUserFavourites',
                'AirlineContactDepartments',
                'AccountSuppliers',
                'FlightBriefCrewMembers',
                'EnquiryStatuses',
                'CustomerSocialMedia',
                'CustomerPortalUserSharedLinks',
                'AccountsCBFCharterBookingView',
                'BookingAccountingDetails',
                'AirplaneHistoryRecords',
                'AircraftETOPS',
                'PriceInclusionTranslations',
                'AccountBookingsView',
                'EnquiryTypes',
                'CrewMemberRoles',
                'PriceInclusions',
                'AircraftTypeView',
                'EmailTemplateTypes',
                'OfficeStateRiskLevels',
                'AircraftCategoryView',
                'Alerts',
                'AccountCostCentres',
                'ComplianceAlertRelevantEnquiryTypes',
                'FlightBriefDocuments',
                'AirlineDepartments',
                'CustomerPortalBookingReadReceipts',
                'PriceExclusionTranslations',
                'AccountPurchaseOrders',
                'FlightBriefLegs',
                'BookingCompetitiveAirlines',
                'AircraftSeatMaterials',
                'SalesReportView_RB1',
                'Activities',
                'SchemaVersions',
                'SalesReportView_PJH2',
                'FlightBriefs',
                'IBOSApiHosts',
                'JetCardTypeTranslations',
                'AssistingOfficeAccountOverrides',
                'CustomerPortalItineraryCrewMembers',
                'SalesReportView_PJH',
                'EmailTemplateImages',
                'AdditionalCostAudits',
                'DocumentTemplateDepartments',
                'CustomerPortalUserBookingReadReceipts',
                'AirlineRequestForQuotePriceInclusions',
                'SalesBoundaryCountriesView',
                'FlightReportDocuments',
                'PrimaryContactView',
                'AdditionalCostCategories',
                'IBOSApiKeys',
                'OpenEnquiries',
                'FlightReportLegs',
                'EnquiryFiles',
                'OfficeLocations',
                'AdditionalCostRecipients',
                'Amenities',
                'Images',
                'FlightReports',
                'EmailTemplateDepartments',
                'AirlineRequestForQuotePriceExclusions',
                'CustomerBrokerView',
                'AdditionalCosts',
                'AirlineRequestImages',
                'Customerbrokerview_RB1',
                'GlobalAirlines',
                'Languages',
                'CustomerPortalUserOneSignalPushNotificationIds',
                'AirlineRequestForQuoteSpecificRequirements',
                'AirlineContacts',
                'BridgerCheckRequestResults',
                'AircraftTypeModels',
                'LegsOld',
                'MarketingRefusalReasons',
                'BookingBridgerChecks',
                'LoginAttemptLogs',
                'UserListAnalytics',
                'CustomerPortalQuotes',
                'AirlineRequestLegs',
                'PublishedFlightBriefLocations',
                'IntercompanyCosts',
                'CustomerSearchListCustomers',
                'AirlineRequestForQuoteAirlineContacts',
                'CustomerPortalUserAccountVerificationTokens',
                'BookingCompetitors',
                'MovementTypes',
                'PublishedItineraryLegs',
                'IWASPublishingApiKeys',
                'AirlineRequests',
                'CustomerPortalUserPasswordResetTokens',
                'AirlineLocationTelephoneNumbers',
                'Airlines',
                'BookingAccountingProjectCodes',
                'DuplicateCheckAuditLogs',
                'OfficeReferrals',
                'AccessDimensionsDatabases',
                'AirlineRequestForQuoteAirlineEmails',
                'Sites',
                'Offices',
                'AirplaneHistories',
                'LoyaltyTransactions',
                'UserSites',
                'EmailTemplateImageOptimisations',
                'AirlineContactTypes',
                'LoyaltyGiftCategories',
                'Operators',
                'Airplanes',
                'AirlineRequestForQuoteAircraftTypes',
                'CustomerContactTypes',
                'IndividualUserTargetValues',
                'AutomatedContractSelectionConfig',
                'IndividualAircraftAirlines',
                'AirportContacts',
                'AircraftTypeManufacturers',
                'OperatorsTemp',
                'FlightReportLogs',
                'Airports',
                'QuoteAmenities',
                'ListAnalytics',
                'EnquiryExpectedPassengers',
                'PasswordLogs',
                'ApplicationEvents',
                'TempContactSocialMedia',
                'BrokerAllocationRequests',
                'SalesBoundaryCountries',
                'PasswordResetTickets',
                'AuditLogs',
                'CustomerPortalUserLinks',
                'ItineraryLegPassengers',
                'PublishedQuoteLegs',
                'AirlineContactSelectedLocations',
                'Competitors',
                'CustomerPortalItineraryParts',
                'UserTasks',
                'Quotes',
                'BlacklistSources',
                'BankAccounts',
                'AdditionalInformationDefaults',
                'SharedCustomerContacts',
                'Trips',
                'RecordChangeTypes',
                'IndividualAircraftCategoryCApprovals',
                'BookingContacts',
                'CustomerPortalAppVersions',
                'FocusedListAnalytics',
                'ClientVersionLogs',
                'CustomerSourceCategories',
                'RoleCategories',
                'BookingContactTypes',
                'SocialMediaTypes',
                'ContactConsents',
                'CustomerPortalUserNotifications',
                'AutomatedBookingUserTaskTypes',
                'Roles',
                'QuoteSharingLogs',
                'BookingListTypes',
                'TripLegs',
                'SalesBoundaries',
                'BookingPricings',
                'PublishedFlightBriefLegs',
                'sysdiagrams',
                'FileServerAccesses',
                'FlightBriefLocations',
                'OperatorHistoryRecords',
                'AutomatedBookingUserTasks',
                'SalesBoundaryStates',
                'Bookings',
                'AirlineRequestPriceExclusions',
                'CustomerPortalItineraryPassengers',
                'SalesReports',
                'BookingStatuses',
                'BaseLegs',
                'CustomerJetCardRates',
                'AirlineRequestAmenities',
                'SalesReportTypes',
                'AirlineLocations',
                'AirlineRequestPriceInclusions',
                'SearchAudits',
                'CustomerPortalModificationRequests',
                'CargoTypes',
                'AirlineImages',
                'DepartmentUserTargetValues',
                'CustomerPortalQuoteLegs',
                'Settings',
                'CarouselImages',
                'LockedBookingPermittedUserGroups',
                'Sports',
                'OtherAccountingCosts',
                'CloseReasons',
                'CustomerTypeCategories',
                'OfficeCountryRiskLevels',
                'QuotePriceExclusions',
                'BookingSnapshots',
                'CateringRequirements',
                'UserTeamLeaders',
                'PublishedEnquiryLegs',
                'TempLegs',
                'ItineraryLegLocations',
                'Contacts_PreferredSports',
                'CommonEmailDomains',
                'BrokerAllocateToMeLogs',
                'CountryCodes',
                'TimeTypes',
                'ComplianceSnapshots',
                'Reports',
                'ContentBlocks',
                'AccountCustomers',
                'SpecificRequirements',
                'BookingComplianceAirplanes',
                'Timezones',
                'Contracts',
                'PublishedTrips',
                'PdfLicenceUses',
                'TripReasons',
                'JournalEntries',
                'Countries',
                'AccountCurrencies',
                'BookingSpecificRequirements',
                'AirlineAircraftSearchHistory',
                'PublishedTripLegs',
                'CustomerSearchLists',
                'BaseContactSocialMedia',
                'UserGroupMemberships',
                'Currencies',
                'AllocationSources',
                'CargoTypeCategories',
                'UserGroupRoles',
                'CurrencyRates',
                'BookingCateringRequirements',
                'AccountsConfirmationMessageLogs',
                'CustomerPortalNotifications',
                'UserRefreshTokens',
                'UserGroups',
                'ComplianceAlerts',
                'CustomerBrokers',
                'CustomerCodeLogs',
                'PublishedItineraryLegCrewMembers',
                'CustomerPortalTrips',
                'CustomerPortalItineraryLocations',
                'Users',
                'CustomerCodes',
                'AircraftImages',
                'AirlineRequestSpecificRequirements',
                'UserSalesBoundaryView',
                'TripReasonCategories',
                'AircraftTypeCategories',
                'IndividualAircraftHistoricTailNumbers',
                'CustomerPortalTripLegs',
                'UserSalesBoundaries',
                'UserBrokerSiteView',
                'CustomerContacts',
                'AirlineAircraftSearchHistoryDepartments',
                'UserGroup_UserView',
                'WeightUnits',
                'SalesReportTypeCategories',
                'CustomerPortalQuoteImages',
                'ModificationRequests',
                'PublishedItineraryLegPassengers',
                'UserGroup_ReportLevelView',
                'Customers',
                'IBOSMobileServers',
                'FileStorageLocations',
                'AirlineRequestCateringRequirements',
                'UserProfileReportView',
                'AvinodeAircraftTypes',
                'AirlineAircraftSearchHistoryAircraftTypeModels',
                'CustomerPortalUserSharedLinkUsers',
                'PendingRiskBandedChecks',
                'ListAnalyticEvents',
                'CustomerSources',
                'MasterContactView',
                'BaseFiles',
                'LoyaltyOrders',
                'UserTargetCategories',
                'LegView',
                'DepositTypes',
                'BookingDepartures2',
                'CustomerContactDetailsView',
                'CustomerPortalAirlineRequestDefaults',
                'CustomerPassengers',
                'CustomerCurrentBrokerView',
                'GlobalCompanies',
                'UserTargetValues',
                'AirlineLocationEmailAddresses',
                'LoyaltyGifts',
                'AircraftCategories',
                'AnyAllAirplaneOperators',
                'CustomerCompetitors',
                'OfficeAirlineView',
                'Addresses',
                'Departments',
                'QuoteImages',
                'AirlineRequestForQuoteCateringRequirements',
                'InsuranceHistories',
                'Insurances',
                'IndividualAircraft',
                'AircraftTypeMerge',
                'EventLogs',
                'AircraftTypes',
                'InvoiceChanges',
                'Regions',
                'DocumentTemplatePlacements',
                'States',
                'ContactDetails',
                'LockedBookingPermittedUsers',
                'CustomerTypes',
                'QuoteTranslations',
                'TempContacts',
                'ContactMoods',
                'UserTeams',
                'LatestCustomerCodes2',
                'QuotePriceInclusions',
                'TempContacts_PreferredActivities',
                'ContactsOld',
                'CustomerPortalBookings',
                'CustomerCodeView',
                'Devices',
                'ProformaInvoices',
                'LoyaltyOrderGifts',
                'AirlineAircraftSearchHistoryAircraftTypes',
                'UserDivisionView',
                'BookingDepartures',
                'CustomerPassengerPreferences',
                'ListAnalyticCategories',
                'ItineraryLegCrewMembers',
                'Reference_CustomerCodeView',
                'CustomerPortalUserLinkInvites',
                'CustomerContactDirectoryView',
                'BaseContacts',
                'ContactView',
                'DocumentTemplates',
                'CustomerPortalScheduledPublishingActions',
                'AirportTranslations',
                'CharterBookingView',
                'UserTargetInformation',
                'FavouriteAirlineContacts',
                'SharedLinkOneSignalPushNotificationIds',
                'CharterBooking_OpsDetailsView',
                'DocumentTemplateTypes',
                'AirlineAircraftSearchHistoryAircraftBaseCountries',
                'FlightBriefPassengers',
                'SalesReportView',
                'ItineraryLegs',
                'AirlineOperatorMerge',
                'AmenityTranslations',
                'AirlineRequestForQuoteStatusChangeLogs',
                'CustomerBrokerView_PMR2',
                'EmailGroups',
                'ContactsView',
                'CharterEnquiryview_RB1',
                'EmailQueueItems',
                'CharterEnquiryView',
                'AirlineAircraftSearchHistoryAirlineBaseRegions',
                'UserDepartments',
                'PublishedFlightBriefPassengers',
                'CustomerSearchListAssignees',
                'BusinessTypeView',
                'AircraftTypeImages',
                'ComplianceBridgerConfig',
                'AirlineRequestForQuoteLegs',
                'AirportView',
                'JetCardTypes',
                'AirlineRequestForQuoteAuditLogs',
                'AirlineAircraftSearchHistoryAircraftBaseRegions',
                'CustomerPortalSharedLinkNotifications',
                'AirlineRequestForQuotes',
                'CustomerView',
                'DocumentTemplateOffices',
                'TempContacts_PreferredSports',
                'Contacts_PreferredActivities',
                'PublishedFlightBriefCrewMembers',
                'JobParameter',
                'Set',
                'List',
                'Server',
                'JobQueue',
                'State',
                'Job',
                'Schema',
                'Hash',
                'AggregatedCounter',
                'Counter',
                'Bookings',
                'PublishingCompliantBookingIds',
                'EnquiryLegs',
                'Customers',
                'AirlineRequests',
                'Addresses',
                'ContactDetails',
                'BookingPricings',
                'FlightReports',
                'BaseContacts',
                'CustomerBrokers',
                'CustomerContacts',
                'AdditionalCosts',
            ])
        ]
    }

    addPlayer(id: string) {
        const newPlayer =  new Player(id, this.settings.startingLives);
        this.players.push(newPlayer)
    }

    addAnswer(guess: string) {
        this.givenAnswers.add(guess);
    }

    setGameIsRunning(value: boolean) {
        this.gameIsRunning = value;
    }
}
