const Player = require("./player.js");
const Prompt = require('./prompt');
module.exports = class GameState {
    players;
    promptOptions;
    selectedPrompt;
    answers = [];
    givenAnswers;
    gameIsRunning;
    defaultTimeout;

    constructor() {
        this.players = [];
        this.givenAnswers = new Set;
        this.gameIsRunning = false;
        this.defaultTimeout = 10;
        this.promptOptions = [
            //new Prompt('Randomly Selected Colours', ['Red', 'Blue', 'Green', 'Yellow']),
            new Prompt('US States', [
                'Alabama',
                'Alaska',
                'Arizona',
                'Arkansas',
                'California',
                'Colorado',
                'Connecticut',
                'Delaware',
                'Florida',
                'Georgia',
                'Hawaii',
                'Idaho',
                'Illinois',
                'Indiana',
                'Iowa',
                'Kansas',
                'Kentucky',
                'Louisiana',
                'Maine',
                'Maryland',
                'Massachusetts',
                'Michigan',
                'Minnesota',
                'Mississippi',
                'Missouri',
                'Montana',
                'Nebraska',
                'Nevada',
                'New Hampshire',
                'New Jersey',
                'New Mexico',
                'New York',
                'North Carolina',
                'North Dakota',
                'Ohio',
                'Oklahoma',
                'Oregon',
                'Pennsylvania',
                'Rhode Island',
                'South Carolina',
                'South Dakota',
                'Tennessee',
                'Texas',
                'Utah',
                'Vermont',
                'Virginia',
                'Washington',
                'West Virginia',
                'Wisconsin',
                'Wyoming',
            ]),
            new Prompt('Elements in the Periodic Table', [
                'Hydrogen',
                'Helium',
                'Lithium',
                'Beryllium',
                'Boron',
                'Carbon',
                'Nitrogen',
                'Oxygen',
                'Fluorine',
                'Neon',
                'Sodium',
                'Magnesium',
                'Aluminum',
                'Silicon',
                'Phosphorus',
                'Sulfur',
                'Chlorine',
                'Argon',
                'Potassium',
                'Calcium',
                'Scandium',
                'Titanium',
                'Vanadium',
                'Chromium',
                'Manganese',
                'Iron',
                'Cobalt',
                'Nickel',
                'Copper',
                'Zinc',
                'Gallium',
                'Germanium',
                'Arsenic',
                'Selenium',
                'Bromine',
                'Krypton',
                'Rubidium',
                'Strontium',
                'Yttrium',
                'Zirconium',
                'Niobium',
                'Molybdenum',
                'Technetium',
                'Ruthenium',
                'Rhodium',
                'Palladium',
                'Silver',
                'Cadmium',
                'Indium',
                'Tin',
                'Antimony',
                'Tellurium',
                'Iodine',
                'Xenon',
                'Cesium',
                'Barium',
                'Lanthanum',
                'Cerium',
                'Praseodymium',
                'Neodymium',
                'Promethium',
                'Samarium',
                'Europium',
                'Gadolinium',
                'Terbium',
                'Dysprosium',
                'Holmium',
                'Erbium',
                'Thulium',
                'Ytterbium',
                'Lutetium',
                'Hafnium',
                'Tantalum',
                'Wolfram',
                'Rhenium',
                'Osmium',
                'Iridium',
                'Platinum',
                'Gold',
                'Mercury',
                'Thallium',
                'Lead',
                'Bismuth',
                'Polonium',
                'Astatine',
                'Radon',
                'Francium',
                'Radium',
                'Actinium',
                'Thorium',
                'Protactinium',
                'Uranium',
                'Neptunium',
                'Plutonium',
                'Americium',
                'Curium',
                'Berkelium',
                'Californium',
                'Einsteinium',
                'Fermium',
                'Mendelevium',
                'Nobelium',
                'Lawrencium',
                'Rutherfordium',
                'Dubnium',
                'Seaborgium',
                'Bohrium',
                'Hassium',
                'Meitnerium',
                'Darmstadtium',
                'Roentgenium',
                'Copernicium',
                'Nihonium',
                'Flerovium',
                'Moscovium',
                'Livermorium',
                'Tennessine',
                'Oganesson',
            ])
        ]
    }

    addPlayer(id) {
        const newPlayer =  new Player(id);
        this.players.push(newPlayer)
    }

    addAnswer(guess) {
        this.givenAnswers.add(guess);
    }

    setGameIsRunning(value) {
        this.gameIsRunning = value;
    }
}
